<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Admin\Sanksi;
use App\Models\Admin\Datamahasiswa;
use App\Models\User;
use Carbon\Carbon;

class SanksiDummySeeder extends Seeder
{
    public function run()
    {
        // 1. Ensure we have students to attach sanctions to
        $students = Datamahasiswa::all();

        if ($students->isEmpty()) {
            $this->command->info('Tidak ada data mahasiswa. Membuat 5 mahasiswa dummy...');
            
            for ($i = 1; $i <= 5; $i++) {
                // Create User for Mahasiswa
                $user = User::create([
                    'name' => "Mahasiswa Dummy $i",
                    'email' => "mhs_dummy_$i@univ.ac.id",
                    'password' => bcrypt('password'), // default password
                    'role' => 'mahasiswa'
                ]);

                // Create Datamahasiswa linked to User
                $students->push(Datamahasiswa::create([
                    'id_user' => $user->id_user,
                    'nim' => '2024' . str_pad($i, 5, '0', STR_PAD_LEFT), // e.g. 202400001
                    'nama' => $user->name,
                    'email' => $user->email,
                    'semester' => rand(1, 8),
                    'ipk' => rand(300, 400) / 100, // 3.00 - 4.00
                ]));
            }
        }

        $this->command->info('Membuat 11 Data Sanksi Dummy...');

        $jenisSanksi = ['Ringan', 'Sedang', 'Ringan', 'Sedang', 'Ringan', 'Ringan', 'Sedang', 'Ringan', 'Sedang', 'Ringan', 'Sedang'];
        $hukumanList = [
            'Teguran Lisan', 
            'Surat Peringatan 1', 
            'Teguran Tertulis', 
            'Skorsing 3 Hari', 
            'Teguran Lisan', 
            'Wajib Lapor', 
            'Pencabutan Hak Akses Fasilitas', 
            'Teguran Lisan', 
            'Surat Peringatan 2', 
            'Pembinaan Konseling', 
            'Skorsing 1 Minggu'
        ];
        
        $count = 0;
        foreach($jenisSanksi as $index => $jenis) {
            $student = $students->random(); // Pick random student

            Sanksi::create([
                'id_mahasiswa' => $student->id_mahasiswa,
                'jenis_sanksi' => $jenis,
                'jenis_hukuman' => $hukumanList[$index],
                'tanggal_sanksi' => Carbon::now()->subDays(rand(1, 30)), // Random date within last 30 days
                'keterangan' => 'Sanksi dummy generated by seeder.',
            ]);
            $count++;
        }

        $this->command->info("Berhasil membuat $count data sanksi dummy!");
    }
}
